/* Copyright (c) 2020 Jakob Meng, <jakobmeng@web.de>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef EDAMER_DT_MATRIX_DISTRIBUTION_IMPL_HPP
#define EDAMER_DT_MATRIX_DISTRIBUTION_IMPL_HPP

#include "fwd.hpp"

#include <boost/hana/drop_back.hpp>
#include <boost/hana/tuple.hpp>
#include <edamer/config.hpp>
#include <edamer/detail/pybind11.hpp>
#ifdef HBRS_MPL_ENABLE_ELEMENTAL
	#include <El.hpp>
#endif // HBRS_MPL_ENABLE_ELEMENTAL

EDAMER_NAMESPACE_BEGIN(EDAMER_NAMESPACE)
namespace hana = boost::hana;

#ifdef HBRS_MPL_ENABLE_ELEMENTAL
static auto el_matrix_distributions = hana::drop_back(hana::make_tuple(
	//TODO: Add BLOCK distribution wrappings
	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_CIRC_CIRC
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::CIRC), EDAMER_INTEGRAL_NAME_PAIR(El::CIRC), EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_CIRC_CIRC

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_MC_MR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::MC),   EDAMER_INTEGRAL_NAME_PAIR(El::MR),   EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_MC_MR

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_MC_STAR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::MC),   EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_MC_STAR

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_MD_STAR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::MD),   EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_MD_STAR

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_MR_MC
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::MR),   EDAMER_INTEGRAL_NAME_PAIR(El::MC),   EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_MR_MC

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_MR_STAR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::MR),   EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_MR_STAR

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_MC
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::MC),   EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_MC

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_MD
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::MD),   EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_MD

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_MR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::MR),   EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_MR

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_STAR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_STAR

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_VC
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::VC),   EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_VC

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_VR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::VR),   EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_STAR_VR

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_VC_STAR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::VC),   EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_VC_STAR

	#ifdef EDAMER_ENABLE_MATRIX_DISTRIBUTION_VR_STAR
		hana::make_tuple(EDAMER_INTEGRAL_NAME_PAIR(El::VR),   EDAMER_INTEGRAL_NAME_PAIR(El::STAR), EDAMER_INTEGRAL_NAME_PAIR(El::ELEMENT)),
	#endif // EDAMER_ENABLE_MATRIX_DISTRIBUTION_VR_STAR
	
	"SEQUENCE_TERMINATOR___REMOVED_BY_DROP_BACK"
));
#endif // HBRS_MPL_ENABLE_ELEMENTAL

template <>
struct EDAMER_API pydef_impl<hbrs::mpl::matrix_distribution_tag> {
	static py::module &
	apply(py::module & m, py::module & base);
};

EDAMER_NAMESPACE_END(EDAMER_NAMESPACE)

#endif // !EDAMER_DT_MATRIX_DISTRIBUTION_IMPL_HPP
